SELECT
  T1.DNAME AS DEPT_NAME,
  LISTAGG(T2.ENAME, ',') WITHIN GROUP (ORDER BY T2.ENAME ASC) AS DEPT_MEMBERS
FROM
  SCOTT.DEPT T1
  LEFT OUTER JOIN SCOTT.EMP T2
  ON T1.DEPTNO = T2.DEPTNO
GROUP BY
  T1.DNAME;