-- NVL関数を使わないSQL。
SELECT
  T1.DNAME AS 部署名,
  T2.ENAME AS 社員名
FROM
  SCOTT.DEPT T1
  LEFT OUTER JOIN SCOTT.EMP T2 ON T1.DEPTNO=T2.DEPTNO
WHERE
  T1.DNAME IN ('ACCOUNTING', 'OPERATIONS');


-- NVL関数を使って、部署に紐づく社員が居ない時に「---」を出力するSQL。
SELECT
  T1.DNAME AS 部署名,
  NVL(T2.ENAME, '---') AS 社員名
FROM
  SCOTT.DEPT T1
  LEFT OUTER JOIN SCOTT.EMP T2 ON T1.DEPTNO=T2.DEPTNO
WHERE
  T1.DNAME IN ('ACCOUNTING', 'OPERATIONS');